import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Shadow Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
